
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-httpbin-1
  namespace: liemlhd-monitoring-demo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liemlhd-monitoring-demo-dev-1
  template:
    metadata:
      labels:
        app: liemlhd-monitoring-demo-dev-1
    spec:
      containers:
        - name: go-httpbin
          image: saboteurkid/go-httpbin:58f8a3b3
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /status/200
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /status/200
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: go-httpbin-1
  namespace: liemlhd-monitoring-demo-dev
spec:
  selector:
    app: liemlhd-monitoring-demo-dev-1
  ports:
    - name: http
      port: 8080
      targetPort: 8080
